### ISSUE TITLE
custom-element自定义html标签混合开发报错异常问题

### ISSUE THREAD

**Issue by zelllez** [openkraken/kraken#1369]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

0.10.x

### 重现步骤 ｜ Steps To Reproduce

按照集成测试的例子跑一个custom-element例子，启动报错。

![](https://i.ibb.co/vBrXYgb/8971651204957-pic.png)

**重现代码 | Code example:** 

```yaml
name: myflutter01
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  cached_network_image: ^3.0.0
  flutter_screenutil: ^5.0.1
  dio: ^4.0.4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  pigment: ^1.0.4
  kraken: ^0.10.4
  waterfall_flow: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
```dart
import 'package:flutter/material.dart';
import 'package:kraken/kraken.dart';
import 'package:waterfall_flow/waterfall_flow.dart';

void main() {
  Kraken.defineCustomElement('waterfall-flow', (BindingContext? context) {
    return WaterfallFlowWidgetElement(context);
  });
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final bundleContent = '''
 const flutterContainer = document.createElement('waterfall-flow');
    flutterContainer.style.height = '100vh';
    flutterContainer.style.display = 'block';
    const colors = ['red', 'yellow', 'black', 'blue', 'green'];
    for (let i = 0; i < 10; i++) {
      const div = document.createElement('div');
      div.style.width = '100%';
      div.style.border = `1px solid \${colors[i % colors.length]}`;
      div.appendChild(document.createTextNode(`\${i}`));

      const img = document.createElement('img');
      img.src = 'https://gw.alicdn.com/tfs/TB1CxCYq5_1gK0jSZFqXXcpaXXa-128-90.png';
      div.appendChild(img);
      img.style.width = '100px';

      flutterContainer.appendChild(div);
    }
    document.body.appendChild(flutterContainer);
  ''';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Kraken(
          bundle: KrakenBundle.fromContent(bundleContent),
        ),
      ),
    );
  }
}

class WaterfallFlowWidgetElement extends WidgetElement {
  WaterfallFlowWidgetElement(BindingContext? context) : super(context);

  List<Widget> _children = [];

  Widget _func(BuildContext context, int index) {
    return _children[index];
  }

  @override
  Widget build(BuildContext context, Map<String, dynamic> properties, List<Widget> children) {
    _children = children;

    return WaterfallFlow.builder(
      itemBuilder: _func,
      padding: EdgeInsets.all(5.0),
      gridDelegate: SliverWaterfallFlowDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2,
        crossAxisSpacing: 5.0,
        mainAxisSpacing: 5.0,
        lastChildLayoutTypeBuilder: (index) =>
            index == children.length ? LastChildLayoutType.foot : LastChildLayoutType.none,
      ),
    );
  }
}

```

**预期结果 ｜ Expected results:** 
正常展示不报错

**实际结果 ｜ Actual results:** 
报错显示红框
