### ISSUE TITLE
父子选择器、元素选择器不生效

### ISSUE THREAD

**Issue by OneeMe** [openkraken/kraken#150]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
master

### 重现步骤 ｜ Steps To Reproduce
1.在 [Demo](https://github.com/OneeMe/PlayRax) 中执行 npm run start
2. 用 kraken 运行 Demo 中的 css 页面（http://localhost:3333/kraken/css.js）

**重现代码 | Code example:**
[Demo](https://github.com/OneeMe/PlayRax)

**预期结果 ｜ Expected results:** 
和 Web 一样，父子选择器生效，“this is two” 是绿色的：
```css
#box>.container {
    color: green;
}
```
同时元素选择器生效，“this is one” 是紫色的：
```css
div {
    color: blueviolet;
}
```
渲染结果：
<img width="454" alt="image" src="https://user-images.githubusercontent.com/8003181/114364390-ecd49600-9bab-11eb-9515-c8dccf34b6f9.png">

**实际结果 ｜ Actual results:** 
父子选择器、元素选择器不生效，文本没有变色：
<img width="365" alt="image" src="https://user-images.githubusercontent.com/8003181/114364638-2c02e700-9bac-11eb-9616-2d4372c72bee.png">
