### ISSUE TITLE
flutter run之后报错: Unhandled Exception: HandshakeException: Handshake error in client

### ISSUE THREAD

**Issue by xtzero** [openkraken/kraken#250]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

```
➜  myapp kraken --version
0.7.2

➜  myapp dart --version
Dart SDK version: 2.10.0 (stable) (Mon Sep 28 09:21:23 2020 +0200) on "macos_x64"

➜  myapp flutter --version
Flutter 1.22.0 • channel unknown • unknown source
Framework • revision d408d302e2 (7 months ago) • 2020-09-29 11:49:17 -0700
Engine • revision 5babba6c4d
Tools • Dart 2.10.0

```

### 重现步骤 ｜ Steps To Reproduce

- 下载新demo

```sh
$ flutter create myapp
$ cd myapp
```

- 按照[文档](https://openkraken.com/guide/native/interpolation-flutter)修改pubspec.yaml
> dependencies:
> kraken: '>= 0.0.1' # 会安装最新的 kraken 依赖

```sh
$ flutter pub get
```

- 按照[文档](https://openkraken.com/guide/native/interpolation-flutter)修改main.dart
> 打开 lib/main.dart，然后粘贴如下代码：
> ...

- 运行
```sh
$ flutter run
```

**重现代码 | Code example:** 

> pubspec.yaml

```
name: myapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  kraken: '>= 0.0.1'


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

> 控制台运行结果

```
➜  myapp flutter run   
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
 
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         8.0s
Xcode build done.                                           20.3s
Waiting for iPhone 12 Pro Max to report its views...                 3ms
Syncing files to device iPhone 12 Pro Max...                       256ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on iPhone 12 Pro Max is available at: http://127.0.0.1:63129/-anavTArU4w=/
flutter: Kraken DevTool listening at ws://192.168.1.67:9222
flutter: Open Chrome/Edge and paste following url to your navigator:
flutter:     devtools://devtools/bundled/inspector.html?ws=192.168.1.67:9222
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
        CERTIFICATE_VERIFY_FAILED: ok(handshake.cc:354))
```
**预期结果 ｜ Expected results:** 
模拟器正常运行demo

**实际结果 ｜ Actual results:** 
模拟器白屏，控制台出现异常：
```
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
        CERTIFICATE_VERIFY_FAILED: ok(handshake.cc:354))
```

> 模拟器显示
![image](https://user-images.githubusercontent.com/32516078/116349782-58ad3480-a823-11eb-9ad6-6812527793d9.png)
