### ISSUE TITLE
background-size 赋值内容为数值时会不生效

### ISSUE THREAD

**Issue by airingursb** [openkraken/kraken#519]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

0.8.1

### 重现步骤 ｜ Steps To Reproduce

![image](https://user-images.githubusercontent.com/10513408/126283512-1f581034-f4dc-48f3-9aa0-eba5b0bf2b71.png)

**重现代码 | Code example:** 

rax demo

```
<View className={styles.background}/>
```

```css
.background {
  width: 200rpx;
  height: 200rpx;
  background-image: url('//gw.alicdn.com/tfs/TB1MRC_cvb2gK0jSZK9XXaEgFXa-1701-1535.png');
  background-size: 37rpx;
}
```

**预期结果 ｜ Expected results:** 

和浏览器表现一样，生效

**实际结果 ｜ Actual results:** 

和浏览器表现不一样，size 的样式不生效。
