### ISSUE TITLE
display: silver 渲染异常

### ISSUE THREAD

**Issue by temper357** [openkraken/kraken#75]
Demo project: 

```javascript
/** @jsx createElement */
import { createElement } from 'rax';
import './index.css';

export default function App({ location }) {
  return (
    <div className="container">
      {
        new Array(100).fill(1).map((item, index) => (
          <div className="item" key={index}>
            <img className="item-img" src="https://gw.alicdn.com/tfs/TB1K8ZEtRBh1e4jSZFhXXcC9VXa-641-571.png" />
            <p className="item-content">
            《哆啦A梦》为日本漫画家藤子·F·不二雄笔下著名的儿童、科幻漫画作品，自1969年12月开始连载，共发行单行本45册、原著大长篇漫画17本，至今已成为日本国民级长寿动漫。
            </p>
            <span className="tag">{index}</span>
          </div>
        ))
      }
    </div>
  );
}
```

```css
.container {
  width: 750rpx;
  height: 100vh;
  display: sliver;
}

.item {
  position: relative;
  padding: 0 24rpx;
  height: 250rpx;
  line-height: 250rpx;
  background-color: #eee;
  margin-bottom: 10rpx;
  flex-direction: row;
  display: flex;
  align-items: center;
}

.item-img {
  width: 224rpx;
  height: 200rpx;
  margin-right: 18rpx;
}

.item-content {
  flex: 1;
  color: #666;
  font-size: 26rpx;
  line-height: 1.2;
}

.tag {
  position: absolute;
  top: 0;
  right: 0;
  color: #333;
  font-weight: bold;
  font-size: 40rpx;
  line-height: 1;
}
```

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following _CastError was thrown during performLayout():
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      RenderSliverMultiBoxAdaptor.childMainAxisPosition (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:568:36)
#1      RenderSliverHelpers.applyPaintTransformForBoxChild (package:flutter/src/rendering/sliver.dart:1687:20)
#2      RenderSliverMultiBoxAdaptor.applyPaintTransform (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:588:7)
#3      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2392:24)
#4      RenderBox.localToGlobal (package:flutter/src/rendering/box.dart:2372:39)
...
```
